var canvas=document.getElementById('myCanvas');
var ctx=canvas.getContext('2d');
var game_time;
var player_width=40;
var player_height=40;
var player_x=canvas.width/2;
var player_y=canvas.height-player_height;
var player_Vx=3;
var player_Vy=3;    
var rightPressed = false;
var leftPressed = false;
var upPressed = false;
var downPressed = false;
var player_fire_intervals=300;
var bullet_array=[];
var bullet_number=0;
var bullet_out_number=0;
var bullet_speed=5;
var bullet_picture_width=9;
var bullet_picture_height=16.5;
var ufo_width=40.5;
var ufo_height=21;
var ufo_array=[];
var ufo_number=0;
var ufo_that_be_hitted=[];
var bullet_that_hit_ufo=[];
var ufo_bullet_begin_array=[];
var ufo_bullet_speed=3;
var have_set_ufo_bullet_number=0;
var ufo_bullet_array=[];
var ufo_bullet_img_width=8;
var ufo_bullet_img_height=8;
var  player_lives=3;
var animation_position=[];
var animation_array=[];
var have_set_animation=0;
picture_explosion_array=[];
picture_explosion_array[0]='source/explosion.png';
picture_explosion_array[1]='source/explosion2.png';
picture_explosion_array[2]='source/explosion3.png';
picture_explosion_array[3]='source/explosion4.png';
picture_explosion_array[4]='source/explosion5.png';
picture_explosion_array[5]='source/explosion6.png';
picture_explosion_array[6]='source/explosion7.png';
picture_explosion_array[7]='source/explosion8.png';
picture_explosion_array[8]='source/explosion9.png';
var sound_open=false;
var img=new Image();
img.src='source/bg.jpg';
var player1=new player;
var delete_number=0;
var level=0;
var spaceship_width=54;
var spaceship_height=54;
function start_game(){
    var game_start_time=get_time();
    setInterval(set_new_bullet, player_fire_intervals);
    select_level();
    function draw(){
        ctx.clearRect(0, 0, canvas.width, canvas.height); 
        game_time=get_time()-game_start_time;
        draw_bg();
        draw_lives();
        valid_bullet();
        bullet_out_of_screen();
        player1.draw();
        player1.move();
        all_ufo();
        all_ufo_bullet();
        isCollision_playerBullet_and_ufo();
        isCollision_player_and_ufo_bullet();
        all_animation();
        requestAnimationFrame(draw); 
    }
    draw();
    document.addEventListener("keydown", keyDownHandler, false);
    document.addEventListener("keyup", keyUpHandler, false);
    document.addEventListener("touchstart", handleStart, false);
    document.addEventListener("touchend", handleEnd, false);
}